import { Telegraf } from "telegraf";
import { config } from "../config";
import { answerContactQuery } from "../services/llm";

const TRIGGER_WORDS = [
  "who",
  "contact",
  "in charge",
  "reach",
  "responsible",
  "talk to",
  "point of contact",
  "poc",
  "pic",
  "lead",
  "head",
  "founder",
  "superteam",
  "stmy",
  "reach out",
];

const QUESTION_WORDS = ["who", "where", "how", "what", "can"];

function hasTrigger(text: string): boolean {
  const lower = text.toLowerCase();
  const hasTriggerWord = TRIGGER_WORDS.some((w) => lower.includes(w));
  const hasQuestion = QUESTION_WORDS.some((w) => lower.includes(w)) || lower.includes("?");
  return hasTriggerWord && hasQuestion;
}

export function setup(bot: Telegraf): void {
  bot.on("message", async (ctx, next) => {
    if (ctx.chat.type !== "supergroup" && ctx.chat.type !== "group")
      return next();
    if (!("text" in ctx.message) || !ctx.message.text) return next();
    if (!config.openaiApiKey) return next();

    if (!hasTrigger(ctx.message.text)) return next();

    try {
      const OpenAI = (await import("openai")).default;
      const client = new OpenAI({ apiKey: config.openaiApiKey });

      const response = await client.chat.completions.create({
        model: "gpt-4.1-nano",
        messages: [
          {
            role: "system",
            content: `You are a helpful assistant for the Superteam MY community Telegram group.
Answer questions about the community concisely and helpfully.

Key contacts: ${config.picHandles || "not configured"}

Rules:
- Keep answers short (2-4 sentences max)
- If the question is about who to contact, mention the key contacts above
- Be friendly and welcoming
- Don't make up information
- If the question is NOT about the community, contacts, or Superteam, respond with exactly "SKIP"
- If you don't know the answer, respond with exactly "SKIP"`,
          },
          {
            role: "user",
            content: ctx.message.text,
          },
        ],
      });

      const answer = response.choices[0].message.content?.trim();
      if (answer && answer !== "SKIP") {
        await ctx.reply(
          `${answer}\n\n_This answer is generated by AI_`,
          {
            reply_parameters: { message_id: ctx.message.message_id },
            parse_mode: "Markdown",
          },
        );
      } else {
        console.log(`[contactQuery] LLM skipped: "${ctx.message.text}"`);
      }
    } catch (err) {
      console.error("Contact query answer failed:", (err as Error).message);
    }

    return next();
  });
}
